### ISSUE TITLE
The mysql ready function question.

### ISSUE THREAD

**Issue by benzon** [GHMatti/FiveM-MySQL#5]
Hi just wondering if your mysql connection lib requires the usage of mysql.ready? or it will figure it out by it self?

**Comment by benzon** [comment]
The main issue for me here is when i use the onMysqlReady if resource is restartet it wont load ex a ban list unless i have a command to reloadbans after in terminal/rcon

**Comment by ElPumpo** [comment]
**What about until the MySQL stuff is ready?: It waits automatically. So not needed.** from the readme

**Comment by benzon** [comment]
From my experience it dos not wait end up in a soup of failure

**Comment by GHMatti** [comment]
Add a dependency.
